/* eslint-disable */
// ----------------------------------------------------------------------------------------
// Do not edit this file, it is auto-generated by scripts/generate-version.js
// ----------------------------------------------------------------------------------------
export const APP_VERSION_INFO = Object.freeze({
  NAME: '@packages/coding-guide-helper',
  DESCRIPTION: 'Coding guide helper is a chrome extension to help doing pull requests review process.',
  REPOSITORY: 'https://github.com/amwebexpert/chrome-extensions-collection/tree/master/packages/coding-guide-helper',
  AUTHOR: 'amwebexpert@gmail.com',
  VERSION: '1.2.0',
  VERSION_DATE: '2025-02-18',
})

export const LONG_VERSION_DATE = '1.2.0 (2025-02-18)'
